### ISSUE TITLE
Contributing to the package

### ISSUE THREAD

**Issue by llrs** [rgcca-factory/RGCCA#24]
Hi, many thanks for providing RGCCA it has been very useful for my thesis.

A user opened an issue on a package that depends on RGCCA and I noticed there is a branch aiming for a new CRAN release. 

I have made some modifications to RGCCA from the CRAN version 2.1.2 on [a fork](https://github.com/llrs/RGCCA) and perhaps you are interested in some of those to be included.

Some of them are related to the infrastructure: 
- Website with documentation of the package
- Continuous integration test to check state of the package  
- Added many tests
- Created the [gliomaData package on github](https://github.com/llrs/gliomaData) for easier install and testing

Changes relate to code efficiency and simplicity:
- `soft` was speed up.
- Use of `tcrossprod` and `crossprod` whenever possible.
- New functions for AVE calculation.
- Validate input on user-facing functions.
- Split code for (shave methods on its own file, AVE functions on their own...)
- Reduced some functions calls here and there

Some "upgrades":
- Now models can be a list and at each dimension the model can change on `rgcca2` and `sgcca2`

I do not know the extent of the changes but a user complained that the new CRAN branch doesn't export previously exported functions like scale2. It would be nice if you could explain the extend of the changes and provide a release cycle (first .Deprecate the function then in next version mark it as .Defunct) it would help all, users and developers. 

For instance I saw that on #23 there is a PR using the version of gliomaData package I created on Github to make it easier to test and work with the package. 

Thanks and let me know if you want some pull requests.

**Comment by llrs** [comment]
Any update on this?

**Comment by GFabien** [comment]
Hi @llrs! Sorry for the **extremely** late answer... 

First we are really happy that you find the package useful! 

If you're willing to contribute that's great and we would be pleased to integrate your propositions. As you have probably seen, the active branch is the CRAN one and it brings a lot of changes compared to previous versions. Some things have already been simplified but there is definitely room to improve and simplify the code further.

About the changes that were made, as I jumped in this year I don't know either the extent but it would be definitely a good idea to publish a release note to explain them. 

If you want to discuss further you can send an email to @Tenenhaus and I and we can arrange a meeting.

**Comment by llrs** [comment]
Sorry @GFabien I don't have your email but if you are interested I will email @Tenenhaus again (I already had exchanged some emails regarding my modifications on RGCCA with him on 2019).

**Comment by GFabien** [comment]
Sure, you can write to @Tenenhaus and he will add me to the loop.

**Comment by llrs** [comment]
@GFabien I sent an email to @Tenenhaus, hope to meet you soon
