### ISSUE TITLE
Questions about updating code

### ISSUE THREAD

**Issue by llrs** [rgcca-factory/RGCCA#35]
Some time ago a user asked me to make my package compatible with the upcoming RGCCA version https://github.com/llrs/inteRmodel/issues/4. I'm now looking into it as I'll probably be making this transition myself.

However, there are some difficulties when moving from RGCCA 2.1.2 to RGCCA >= 3. I have some questions about what will be kept and I think there are some minor modifications that could make it easier for other developers to adapt packages and scripts to the new version of RGCCA. Probably some of these changes that break the backwards compatibility are conscious decisions you made, so it might not be anything to do on your part but knowing them would help me (and probably others) to adapt the code. 

Hope it is fine to ask and provide feedback here.

**Comment by GFabien** [comment]
Hi @llrs! I totally understand your point and I agree. I think it's a good idea to have this discussion here to document these changes. Generally, the changes/deletions were made to either simplify the code or give more meaningful names to objects.

**Comment by GFabien** [comment]
Hi @llrs! The new version is now available on CRAN! We tried to take into account most of your comments. I'm closing this issue since most of the comments are no longer relevant. Thank you again for your feedback, and do not hesitate to open a new issue for anything.

**Comment by llrs** [comment]
Congratulations on the release. I'm sure it felt good to finally pass the CRAN checks. 
Thanks for letting me know. I might need to use RGCCA soon.

I see you went with completely removing the sgcca function but you kept some old arguments in rgcca. Thanks!

I've seen you had some problems with version 3.0.0 and the current 3.0.1 currently has some errors in the tests too. If you need to release a new version perhaps it would be a good move to document the print and plot methods for the rgcca, rgcca_cv, rgcca_permutation, rgcca_bootstrap, and rgcca_stability classes in a single page for all the classes.
